// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoClover.Server.Context;

#nullable disable

namespace SoClover.Server.Migrations
{
    [DbContext(typeof(SoCloverDBContext))]
    [Migration("20260528182602_NewSeederWords")]
    partial class NewSeederWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoClover.Server.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BottomClue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeftClue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("RightClue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TopClue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("SoClover.Server.Models.BoardSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameRoomCardId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionIndex")
                        .HasColumnType("int");

                    b.Property<int?>("TargetGameRoomCardId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetRotation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("GameRoomCardId")
                        .IsUnique()
                        .HasFilter("[GameRoomCardId] IS NOT NULL");

                    b.HasIndex("TargetGameRoomCardId")
                        .IsUnique()
                        .HasFilter("[TargetGameRoomCardId] IS NOT NULL");

                    b.ToTable("BoardSlots");
                });

            modelBuilder.Entity("SoClover.Server.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WordBottom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WordLeft")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WordRight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WordTop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WordBottom = "Ser",
                            WordLeft = "Ocean",
                            WordRight = "Wulkan",
                            WordTop = "Klawiatura"
                        },
                        new
                        {
                            Id = 2,
                            WordBottom = "Chmura",
                            WordLeft = "Długopis",
                            WordRight = "Piekarnik",
                            WordTop = "Żyrafa"
                        },
                        new
                        {
                            Id = 3,
                            WordBottom = "Beton",
                            WordLeft = "Muzyka",
                            WordRight = "Truskawka",
                            WordTop = "Kompas"
                        },
                        new
                        {
                            Id = 4,
                            WordBottom = "Poduszka",
                            WordLeft = "Teatr",
                            WordRight = "Kaktus",
                            WordTop = "Smarfon"
                        },
                        new
                        {
                            Id = 5,
                            WordBottom = "Musztarda",
                            WordLeft = "Tramwaj",
                            WordRight = "Księżyc",
                            WordTop = "Młotek"
                        },
                        new
                        {
                            Id = 6,
                            WordBottom = "Marchewka",
                            WordLeft = "Zamek",
                            WordRight = "Zegarek",
                            WordTop = "Lodowiec"
                        },
                        new
                        {
                            Id = 7,
                            WordBottom = "Helikopter",
                            WordLeft = "Mydło",
                            WordRight = "Róża",
                            WordTop = "Paszport"
                        },
                        new
                        {
                            Id = 8,
                            WordBottom = "Rower",
                            WordLeft = "Wiatr",
                            WordRight = "Czekolada",
                            WordTop = "Pająk"
                        },
                        new
                        {
                            Id = 9,
                            WordBottom = "Pingwin",
                            WordLeft = "Kebab",
                            WordRight = "Bateria",
                            WordTop = "Parasol"
                        },
                        new
                        {
                            Id = 10,
                            WordBottom = "Drabina",
                            WordLeft = "Jezioro",
                            WordRight = "Cytryna",
                            WordTop = "Mikroskop"
                        },
                        new
                        {
                            Id = 11,
                            WordBottom = "Śrubokręt",
                            WordLeft = "Pustynia",
                            WordRight = "Kura",
                            WordTop = "Gitara"
                        },
                        new
                        {
                            Id = 12,
                            WordBottom = "Pomidor",
                            WordLeft = "Gwiazda",
                            WordRight = "Pociąg",
                            WordTop = "Ręcznik"
                        },
                        new
                        {
                            Id = 13,
                            WordBottom = "Widelec",
                            WordLeft = "Błyskawica",
                            WordRight = "Książka",
                            WordTop = "Krokodyl"
                        },
                        new
                        {
                            Id = 14,
                            WordBottom = "Samolot",
                            WordLeft = "Las",
                            WordRight = "Lustro",
                            WordTop = "Ziemniak"
                        },
                        new
                        {
                            Id = 15,
                            WordBottom = "Kotwica",
                            WordLeft = "Tęcza",
                            WordRight = "Kapusta",
                            WordTop = "Aparat"
                        },
                        new
                        {
                            Id = 16,
                            WordBottom = "Kawa",
                            WordLeft = "Rzeka",
                            WordRight = "Klucz",
                            WordTop = "Słoń"
                        },
                        new
                        {
                            Id = 17,
                            WordBottom = "Czołg",
                            WordLeft = "Góry",
                            WordRight = "Banan",
                            WordTop = "Nożyczki"
                        },
                        new
                        {
                            Id = 18,
                            WordBottom = "Chleb",
                            WordLeft = "Rakieta",
                            WordRight = "Lampa",
                            WordTop = "Delfin"
                        },
                        new
                        {
                            Id = 19,
                            WordBottom = "Motocykl",
                            WordLeft = "Jaskinia",
                            WordRight = "Arbuz",
                            WordTop = "Wieszak"
                        },
                        new
                        {
                            Id = 20,
                            WordBottom = "Patelnia",
                            WordLeft = "Chmury",
                            WordRight = "Zeszyt",
                            WordTop = "Krowa"
                        },
                        new
                        {
                            Id = 21,
                            WordBottom = "Traktor",
                            WordLeft = "Wodospad",
                            WordRight = "Miód",
                            WordTop = "Skarpetka"
                        },
                        new
                        {
                            Id = 22,
                            WordBottom = "Cebula",
                            WordLeft = "Ogień",
                            WordRight = "Portfel",
                            WordTop = "Kangur"
                        },
                        new
                        {
                            Id = 23,
                            WordBottom = "Ciężarówka",
                            WordLeft = "Kosmos",
                            WordRight = "Grzyb",
                            WordTop = "Szklanka"
                        },
                        new
                        {
                            Id = 24,
                            WordBottom = "Talerz",
                            WordLeft = "Zima",
                            WordRight = "Ołówek",
                            WordTop = "Niedźwiedź"
                        },
                        new
                        {
                            Id = 25,
                            WordBottom = "Statek",
                            WordLeft = "Lato",
                            WordRight = "Orzech",
                            WordTop = "Buty"
                        },
                        new
                        {
                            Id = 26,
                            WordBottom = "Samochód",
                            WordLeft = "Plaża",
                            WordRight = "Śliwka",
                            WordTop = "Plecak"
                        },
                        new
                        {
                            Id = 27,
                            WordBottom = "Garnek",
                            WordLeft = "Śnieg",
                            WordRight = "Linijka",
                            WordTop = "Żaba"
                        },
                        new
                        {
                            Id = 28,
                            WordBottom = "Autobus",
                            WordLeft = "Deszcz",
                            WordRight = "Jajko",
                            WordTop = "Czapka"
                        },
                        new
                        {
                            Id = 29,
                            WordBottom = "Nóż",
                            WordLeft = "Mgła",
                            WordRight = "Gumka",
                            WordTop = "Pies"
                        },
                        new
                        {
                            Id = 30,
                            WordBottom = "Łyżka",
                            WordLeft = "Grad",
                            WordRight = "Spinacz",
                            WordTop = "Kot"
                        },
                        new
                        {
                            Id = 31,
                            WordBottom = "Kubek",
                            WordLeft = "Tornado",
                            WordRight = "Kalka",
                            WordTop = "Bocian"
                        },
                        new
                        {
                            Id = 32,
                            WordBottom = "Kieliszek",
                            WordLeft = "Burza",
                            WordRight = "Zszywacz",
                            WordTop = "Zając"
                        },
                        new
                        {
                            Id = 33,
                            WordBottom = "Dzbanek",
                            WordLeft = "Susza",
                            WordRight = "Marker",
                            WordTop = "Wilk"
                        },
                        new
                        {
                            Id = 34,
                            WordBottom = "Miska",
                            WordLeft = "Mroz",
                            WordRight = "Nożyk",
                            WordTop = "Lis"
                        },
                        new
                        {
                            Id = 35,
                            WordBottom = "Rondel",
                            WordLeft = "Upadek",
                            WordRight = "Taśma",
                            WordTop = "Sarna"
                        },
                        new
                        {
                            Id = 36,
                            WordBottom = "Czajnik",
                            WordLeft = "Lawina",
                            WordRight = "Teczka",
                            WordTop = "Dzik"
                        },
                        new
                        {
                            Id = 37,
                            WordBottom = "Toster",
                            WordLeft = "Powódź",
                            WordRight = "Segregator",
                            WordTop = "Wiewiórka"
                        },
                        new
                        {
                            Id = 38,
                            WordBottom = "Blender",
                            WordLeft = "Szron",
                            WordRight = "Klamra",
                            WordTop = "Jeż"
                        },
                        new
                        {
                            Id = 39,
                            WordBottom = "Mikrofalówka",
                            WordLeft = "Rosa",
                            WordRight = "Pieczątka",
                            WordTop = "Mysz"
                        },
                        new
                        {
                            Id = 40,
                            WordBottom = "Zmywarka",
                            WordLeft = "Upał",
                            WordRight = "Koperta",
                            WordTop = "Szczur"
                        },
                        new
                        {
                            Id = 41,
                            WordBottom = "Sofa",
                            WordLeft = "Kogut",
                            WordRight = "Ogórek",
                            WordTop = "Okręt"
                        },
                        new
                        {
                            Id = 42,
                            WordBottom = "Fotel",
                            WordLeft = "Indyk",
                            WordRight = "Czosnek",
                            WordTop = "Bilet"
                        },
                        new
                        {
                            Id = 43,
                            WordBottom = "Krzesło",
                            WordLeft = "Kaczka",
                            WordRight = "Dynia",
                            WordTop = "Moneta"
                        },
                        new
                        {
                            Id = 44,
                            WordBottom = "Stół",
                            WordLeft = "Gęś",
                            WordRight = "Rzodkiewka",
                            WordTop = "Banknot"
                        },
                        new
                        {
                            Id = 45,
                            WordBottom = "Biurko",
                            WordLeft = "Gołąb",
                            WordRight = "Sałata",
                            WordTop = "Port"
                        },
                        new
                        {
                            Id = 46,
                            WordBottom = "Szafa",
                            WordLeft = "Wróbel",
                            WordRight = "Brokuł",
                            WordTop = "Dworzec"
                        },
                        new
                        {
                            Id = 47,
                            WordBottom = "Komoda",
                            WordLeft = "Orzeł",
                            WordRight = "Kalafior",
                            WordTop = "Lotnisko"
                        },
                        new
                        {
                            Id = 48,
                            WordBottom = "Łóżko",
                            WordLeft = "Sokół",
                            WordRight = "Szpinak",
                            WordTop = "Metro"
                        },
                        new
                        {
                            Id = 49,
                            WordBottom = "Materac",
                            WordLeft = "Jastrząb",
                            WordRight = "Por",
                            WordTop = "Taxi"
                        },
                        new
                        {
                            Id = 50,
                            WordBottom = "Kołdra",
                            WordLeft = "Sowa",
                            WordRight = "Seler",
                            WordTop = "Uber"
                        },
                        new
                        {
                            Id = 51,
                            WordBottom = "Koc",
                            WordLeft = "Dzięcioł",
                            WordRight = "Pietruszka",
                            WordTop = "Kajak"
                        },
                        new
                        {
                            Id = 52,
                            WordBottom = "Prześcieradło",
                            WordLeft = "Kukułka",
                            WordRight = "Burak",
                            WordTop = "Ponton"
                        },
                        new
                        {
                            Id = 53,
                            WordBottom = "Dywan",
                            WordLeft = "Bocian",
                            WordRight = "Ziemniak",
                            WordTop = "Rower"
                        },
                        new
                        {
                            Id = 54,
                            WordBottom = "Zasłona",
                            WordLeft = "Jaskółka",
                            WordRight = "Papryka",
                            WordTop = "Skuter"
                        },
                        new
                        {
                            Id = 55,
                            WordBottom = "Roleta",
                            WordLeft = "Słowik",
                            WordRight = "Pomidor",
                            WordTop = "Hulajnoga"
                        },
                        new
                        {
                            Id = 56,
                            WordBottom = "Obraz",
                            WordLeft = "Kanarek",
                            WordRight = "Fasola",
                            WordTop = "Rolki"
                        },
                        new
                        {
                            Id = 57,
                            WordBottom = "Plakat",
                            WordLeft = "Papuga",
                            WordRight = "Groch",
                            WordTop = "Łyżwy"
                        },
                        new
                        {
                            Id = 58,
                            WordBottom = "Rzeźba",
                            WordLeft = "Struś",
                            WordRight = "Kukurydza",
                            WordTop = "Narty"
                        },
                        new
                        {
                            Id = 59,
                            WordBottom = "Wazon",
                            WordLeft = "Pingwin",
                            WordRight = "Soczewica",
                            WordTop = "Snowboard"
                        },
                        new
                        {
                            Id = 60,
                            WordBottom = "Doniczka",
                            WordLeft = "Pelikan",
                            WordRight = "Cieciorka",
                            WordTop = "Sanki"
                        },
                        new
                        {
                            Id = 61,
                            WordBottom = "Telewizor",
                            WordLeft = "Młot",
                            WordRight = "Jabłko",
                            WordTop = "Karp"
                        },
                        new
                        {
                            Id = 62,
                            WordBottom = "Radio",
                            WordLeft = "Piła",
                            WordRight = "Gruszka",
                            WordTop = "Rekin"
                        },
                        new
                        {
                            Id = 63,
                            WordBottom = "Głośnik",
                            WordLeft = "Siekiera",
                            WordRight = "Śliwka",
                            WordTop = "Wieloryb"
                        },
                        new
                        {
                            Id = 64,
                            WordBottom = "Słuchawki",
                            WordLeft = "Kombinerki",
                            WordRight = "Brzoskwinia",
                            WordTop = "Delfin"
                        },
                        new
                        {
                            Id = 65,
                            WordBottom = "Mikrofon",
                            WordLeft = "Klucz",
                            WordRight = "Morela",
                            WordTop = "Orka"
                        },
                        new
                        {
                            Id = 66,
                            WordBottom = "Kamera",
                            WordLeft = "Śruba",
                            WordRight = "Czereśnia",
                            WordTop = "Manta"
                        },
                        new
                        {
                            Id = 67,
                            WordBottom = "Projektor",
                            WordLeft = "Gwóźdź",
                            WordRight = "Wiśnia",
                            WordTop = "Ośmiornica"
                        },
                        new
                        {
                            Id = 68,
                            WordBottom = "Ekran",
                            WordLeft = "Wkręt",
                            WordRight = "Agrest",
                            WordTop = "Kalmar"
                        },
                        new
                        {
                            Id = 69,
                            WordBottom = "Pilot",
                            WordLeft = "Wiertarka",
                            WordRight = "Porzeczka",
                            WordTop = "Meduza"
                        },
                        new
                        {
                            Id = 70,
                            WordBottom = "Antena",
                            WordLeft = "Szlifierka",
                            WordRight = "Malina",
                            WordTop = "Krab"
                        },
                        new
                        {
                            Id = 71,
                            WordBottom = "Kabel",
                            WordLeft = "Młot",
                            WordRight = "Jeżyna",
                            WordTop = "Homar"
                        },
                        new
                        {
                            Id = 72,
                            WordBottom = "Wtyczka",
                            WordLeft = "Łom",
                            WordRight = "Borówka",
                            WordTop = "Krewetka"
                        },
                        new
                        {
                            Id = 73,
                            WordBottom = "Gniazdko",
                            WordLeft = "Kilof",
                            WordRight = "Jagoda",
                            WordTop = "Rak"
                        },
                        new
                        {
                            Id = 74,
                            WordBottom = "Żarówka",
                            WordLeft = "Łopata",
                            WordRight = "Żurawina",
                            WordTop = "Śledź"
                        },
                        new
                        {
                            Id = 75,
                            WordBottom = "Latarka",
                            WordLeft = "Grable",
                            WordRight = "Granat",
                            WordTop = "Dorsz"
                        },
                        new
                        {
                            Id = 76,
                            WordBottom = "Laser",
                            WordLeft = "Siekiera",
                            WordRight = "Mango",
                            WordTop = "Łosoś"
                        },
                        new
                        {
                            Id = 77,
                            WordBottom = "Licznik",
                            WordLeft = "Kosa",
                            WordRight = "Ananas",
                            WordTop = "Pstrąg"
                        },
                        new
                        {
                            Id = 78,
                            WordBottom = "Bateria",
                            WordLeft = "Sierp",
                            WordRight = "Papaja",
                            WordTop = "Sandacz"
                        },
                        new
                        {
                            Id = 79,
                            WordBottom = "Akumulator",
                            WordLeft = "Piła",
                            WordRight = "Awokado",
                            WordTop = "Szczupak"
                        },
                        new
                        {
                            Id = 80,
                            WordBottom = "Transformator",
                            WordLeft = "Dłuto",
                            WordRight = "Kiwi",
                            WordTop = "Okoń"
                        },
                        new
                        {
                            Id = 81,
                            WordBottom = "Pudełko",
                            WordLeft = "Sosna",
                            WordRight = "Ryż",
                            WordTop = "Gitarzysta"
                        },
                        new
                        {
                            Id = 82,
                            WordBottom = "Koszyk",
                            WordLeft = "Dąb",
                            WordRight = "Kasza",
                            WordTop = "Perkusista"
                        },
                        new
                        {
                            Id = 83,
                            WordBottom = "Torba",
                            WordLeft = "Brzoza",
                            WordRight = "Mąka",
                            WordTop = "Pianista"
                        },
                        new
                        {
                            Id = 84,
                            WordBottom = "Worek",
                            WordLeft = "Lipas",
                            WordRight = "Cukier",
                            WordTop = "Skrzypek"
                        },
                        new
                        {
                            Id = 85,
                            WordBottom = "Siatka",
                            WordLeft = "Klon",
                            WordRight = "Sól",
                            WordTop = "Trębacz"
                        },
                        new
                        {
                            Id = 86,
                            WordBottom = "Skrzynia",
                            WordLeft = "Jodła",
                            WordRight = "Pieprz",
                            WordTop = "Wokalista"
                        },
                        new
                        {
                            Id = 87,
                            WordBottom = "Puszka",
                            WordLeft = "Świerk",
                            WordRight = "Papryka",
                            WordTop = "Dyrygent"
                        },
                        new
                        {
                            Id = 88,
                            WordBottom = "Słoik",
                            WordLeft = "Modrzew",
                            WordRight = "Cynamon",
                            WordTop = "Kompozytor"
                        },
                        new
                        {
                            Id = 89,
                            WordBottom = "Butelka",
                            WordLeft = "Topola",
                            WordRight = "Wanilia",
                            WordTop = "Basista"
                        },
                        new
                        {
                            Id = 90,
                            WordBottom = "Karafka",
                            WordLeft = "Wierzba",
                            WordRight = "Imbir",
                            WordTop = "Flecista"
                        },
                        new
                        {
                            Id = 91,
                            WordBottom = "Szpak",
                            WordLeft = "Kasztan",
                            WordRight = "Makaron",
                            WordTop = "Lekarz"
                        },
                        new
                        {
                            Id = 92,
                            WordBottom = "Skowronek",
                            WordLeft = "Orzech",
                            WordRight = "Płatki",
                            WordTop = "Prawnik"
                        },
                        new
                        {
                            Id = 93,
                            WordBottom = "Jastrząb",
                            WordLeft = "Jarzębina",
                            WordRight = "Chrupki",
                            WordTop = "Inżynier"
                        },
                        new
                        {
                            Id = 94,
                            WordBottom = "Kania",
                            WordLeft = "Akacja",
                            WordRight = "Biszkopt",
                            WordTop = "Nauczyciel"
                        },
                        new
                        {
                            Id = 95,
                            WordBottom = "Kruk",
                            WordLeft = "Jesion",
                            WordRight = "Piernik",
                            WordTop = "Kucharz"
                        },
                        new
                        {
                            Id = 96,
                            WordBottom = "Wrona",
                            WordLeft = "Wiąz",
                            WordRight = "Wafel",
                            WordTop = "Fryzjer"
                        },
                        new
                        {
                            Id = 97,
                            WordBottom = "Sroka",
                            WordLeft = "Buk",
                            WordRight = "Herbatnik",
                            WordTop = "Górnik"
                        },
                        new
                        {
                            Id = 98,
                            WordBottom = "Kawka",
                            WordLeft = "Olsza",
                            WordRight = "Suchar",
                            WordTop = "Kierowca"
                        },
                        new
                        {
                            Id = 99,
                            WordBottom = "Gawron",
                            WordLeft = "Grab",
                            WordRight = "Krakers",
                            WordTop = "Pilot"
                        },
                        new
                        {
                            Id = 100,
                            WordBottom = "Zięba",
                            WordLeft = "Cis",
                            WordRight = "Paluszek",
                            WordTop = "Murarz"
                        });
                });

            modelBuilder.Entity("SoClover.Server.Models.GameRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckedPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfAttempts")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckedPlayerId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("SoClover.Server.Models.GameRoomCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRotation")
                        .HasColumnType("int");

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GameRoomId");

                    b.ToTable("GameRoomCards");
                });

            modelBuilder.Entity("SoClover.Server.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReady")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("PlayerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("PlayerGuid")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SoClover.Server.Models.Board", b =>
                {
                    b.HasOne("SoClover.Server.Models.Player", "Player")
                        .WithOne("Board")
                        .HasForeignKey("SoClover.Server.Models.Board", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SoClover.Server.Models.BoardSlot", b =>
                {
                    b.HasOne("SoClover.Server.Models.Board", "Board")
                        .WithMany("BoardSlots")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoClover.Server.Models.GameRoomCard", "GameRoomCard")
                        .WithOne("BoardSlot")
                        .HasForeignKey("SoClover.Server.Models.BoardSlot", "GameRoomCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SoClover.Server.Models.GameRoomCard", "TargetGameRoomCard")
                        .WithOne("TargetBoardSlot")
                        .HasForeignKey("SoClover.Server.Models.BoardSlot", "TargetGameRoomCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Board");

                    b.Navigation("GameRoomCard");

                    b.Navigation("TargetGameRoomCard");
                });

            modelBuilder.Entity("SoClover.Server.Models.GameRoom", b =>
                {
                    b.HasOne("SoClover.Server.Models.Player", "CheckedPlayer")
                        .WithMany()
                        .HasForeignKey("CheckedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CheckedPlayer");
                });

            modelBuilder.Entity("SoClover.Server.Models.GameRoomCard", b =>
                {
                    b.HasOne("SoClover.Server.Models.Card", "Card")
                        .WithMany("GameRoomCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoClover.Server.Models.GameRoom", "GameRoom")
                        .WithMany("GameRoomCards")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("SoClover.Server.Models.Player", b =>
                {
                    b.HasOne("SoClover.Server.Models.GameRoom", "GameRoom")
                        .WithMany("Players")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("SoClover.Server.Models.Board", b =>
                {
                    b.Navigation("BoardSlots");
                });

            modelBuilder.Entity("SoClover.Server.Models.Card", b =>
                {
                    b.Navigation("GameRoomCards");
                });

            modelBuilder.Entity("SoClover.Server.Models.GameRoom", b =>
                {
                    b.Navigation("GameRoomCards");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("SoClover.Server.Models.GameRoomCard", b =>
                {
                    b.Navigation("BoardSlot");

                    b.Navigation("TargetBoardSlot");
                });

            modelBuilder.Entity("SoClover.Server.Models.Player", b =>
                {
                    b.Navigation("Board");
                });
#pragma warning restore 612, 618
        }
    }
}
